import type { ThemeSettings, ThemeId } from "@/types/settings";

export interface ThemePreset {
    id: ThemeId;
    name: string;
    description: string;
    defaults: ThemeSettings;
    /**
     * Featured presets render in the "New & Featured" section at the top
     * of the admin theme picker, with a NEW ribbon. Non-featured presets
     * fall under the "Classic Library" section below.
     */
    featured?: boolean;
}

export const THEME_PRESETS: ThemePreset[] = [
    {
        id: "classic",
        name: "Classic Compact",
        description: "Small thumbnail, compact info, ideal for quick browsing. Current default.",
        defaults: {
            activeTheme: "classic",
            primaryColor: "#059669",
            accentColor: "#f97316",
            grid: { mobile: 1, tablet: 2, desktop: 3, wide: 4 },
            cardStyle: { borderRadius: "2xl" },
            cardLayout: { imageWidth: 35, imagePosition: "left" },
        },
    },
    {
        id: "premium",
        name: "Premium Wholesale",
        description: "Detailed horizontal card with volume pricing tiers, savings badges and quality indicators.",
        defaults: {
            activeTheme: "premium",
            primaryColor: "#059669",
            accentColor: "#f97316",
            grid: { mobile: 1, tablet: 1, desktop: 2, wide: 2 },
            cardStyle: { borderRadius: "lg" },
            cardLayout: { imageWidth: 35, imagePosition: "left" },
        },
    },
    {
        id: "catalog",
        name: "Modern Catalog",
        description: "Medium card with large image on top and clean tier summary below.",
        defaults: {
            activeTheme: "catalog",
            primaryColor: "#059669",
            accentColor: "#f97316",
            grid: { mobile: 1, tablet: 2, desktop: 3, wide: 3 },
            cardStyle: { borderRadius: "xl" },
            cardLayout: { imageWidth: 35, imagePosition: "top" },
        },
    },
    {
        id: "elegant",
        name: "Elegant Minimal",
        description: "Luxury feel with padded images, frosted glass price badge and soft shadows.",
        defaults: {
            activeTheme: "elegant",
            primaryColor: "#059669",
            accentColor: "#f97316",
            grid: { mobile: 1, tablet: 2, desktop: 3, wide: 4 },
            cardStyle: { borderRadius: "2xl" },
            cardLayout: { imageWidth: 35, imagePosition: "top" },
        },
    },
    {
        id: "storefront",
        name: "Bold Storefront",
        description: "Conversion-focused with accent strip, XXL pricing and prominent add-to-cart.",
        defaults: {
            activeTheme: "storefront",
            primaryColor: "#059669",
            accentColor: "#f97316",
            grid: { mobile: 1, tablet: 1, desktop: 2, wide: 3 },
            cardStyle: { borderRadius: "lg" },
            cardLayout: { imageWidth: 30, imagePosition: "left" },
        },
    },
    {
        id: "magazine",
        name: "Magazine",
        description: "Editorial hero images with gradient overlay text, lifestyle showcase feel.",
        defaults: {
            activeTheme: "magazine",
            primaryColor: "#059669",
            accentColor: "#f97316",
            grid: { mobile: 1, tablet: 2, desktop: 3, wide: 3 },
            cardStyle: { borderRadius: "xl" },
            cardLayout: { imageWidth: 35, imagePosition: "top" },
        },
    },
    {
        id: "listpro",
        name: "List Pro",
        description: "Ultra-compact single-row list for power buyers. All info at a glance, fast ordering.",
        defaults: {
            activeTheme: "listpro",
            primaryColor: "#059669",
            accentColor: "#f97316",
            grid: { mobile: 1, tablet: 1, desktop: 1, wide: 1 },
            cardStyle: { borderRadius: "lg" },
            cardLayout: { imageWidth: 20, imagePosition: "left" },
        },
    },
    {
        id: "metro",
        name: "Bold Metro",
        description: "Material-style tiles with bold color header band and flat clean body.",
        defaults: {
            activeTheme: "metro",
            primaryColor: "#059669",
            accentColor: "#f97316",
            grid: { mobile: 1, tablet: 2, desktop: 3, wide: 4 },
            cardStyle: { borderRadius: "md" },
            cardLayout: { imageWidth: 35, imagePosition: "top" },
        },
    },
    {
        id: "polaroid",
        name: "Polaroid Snap",
        description: "Retro photo-print cards with thick white borders, slight tilt on hover and pinned price tags.",
        defaults: {
            activeTheme: "polaroid",
            primaryColor: "#059669",
            accentColor: "#f97316",
            grid: { mobile: 1, tablet: 2, desktop: 3, wide: 4 },
            cardStyle: { borderRadius: "sm" },
            cardLayout: { imageWidth: 35, imagePosition: "top" },
        },
    },
    {
        id: "glass",
        name: "Glassmorphism",
        description: "Modern frosted-glass cards with backdrop blur, translucent layers and subtle glow accents.",
        defaults: {
            activeTheme: "glass",
            primaryColor: "#059669",
            accentColor: "#6366f1",
            grid: { mobile: 1, tablet: 2, desktop: 3, wide: 4 },
            cardStyle: { borderRadius: "2xl" },
            cardLayout: { imageWidth: 35, imagePosition: "top" },
        },
    },
    {
        id: "darkluxe",
        name: "Dark Luxe",
        description: "Premium dark-mode cards with gold accent pricing, cinematic images and luxury spacing.",
        defaults: {
            activeTheme: "darkluxe",
            primaryColor: "#059669",
            accentColor: "#f59e0b",
            grid: { mobile: 1, tablet: 2, desktop: 3, wide: 3 },
            cardStyle: { borderRadius: "xl" },
            cardLayout: { imageWidth: 35, imagePosition: "top" },
        },
    },
    {
        id: "editorial",
        name: "Editorial",
        description: "Vintage newspaper-style cards with serif headings, dashed borders and editorial print feel.",
        defaults: {
            activeTheme: "editorial",
            primaryColor: "#059669",
            accentColor: "#dc2626",
            grid: { mobile: 1, tablet: 2, desktop: 3, wide: 4 },
            cardStyle: { borderRadius: "none" },
            cardLayout: { imageWidth: 35, imagePosition: "top" },
        },
    },
    {
        id: "neonpop",
        name: "Neon Pop",
        description: "Vibrant gradient-bordered cards with bold colors, playful badges and energetic hover effects.",
        defaults: {
            activeTheme: "neonpop",
            primaryColor: "#8b5cf6",
            accentColor: "#ec4899",
            grid: { mobile: 1, tablet: 2, desktop: 3, wide: 4 },
            cardStyle: { borderRadius: "2xl" },
            cardLayout: { imageWidth: 35, imagePosition: "top" },
        },
    },
    {
        id: "mandi",
        name: "Mandi Board",
        description: "Indian wholesale mandi rate board aesthetic. Dark green, LED-style monospace prices, glowing active tier. Telugu names prominent.",
        defaults: {
            activeTheme: "mandi",
            primaryColor: "#059669",
            accentColor: "#f59e0b",
            grid: { mobile: 1, tablet: 2, desktop: 2, wide: 3 },
            cardStyle: { borderRadius: "lg" },
            cardLayout: { imageWidth: 25, imagePosition: "left" },
        },
    },
    {
        id: "slab",
        name: "Smart Slab",
        description: "Clean minimal design where tier pricing is the hero. Active slab highlighted, progress bar to next tier, savings calculator.",
        defaults: {
            activeTheme: "slab",
            primaryColor: "#059669",
            accentColor: "#f97316",
            grid: { mobile: 1, tablet: 2, desktop: 3, wide: 3 },
            cardStyle: { borderRadius: "xl" },
            cardLayout: { imageWidth: 30, imagePosition: "left" },
        },
    },
    {
        id: "tierstep",
        name: "Tier Steps",
        description: "Visual stepped price ladder. Each tier is a colored step block. Active step elevated with glow. Next-tier nudge with savings.",
        defaults: {
            activeTheme: "tierstep",
            primaryColor: "#059669",
            accentColor: "#f97316",
            grid: { mobile: 1, tablet: 2, desktop: 3, wide: 3 },
            cardStyle: { borderRadius: "2xl" },
            cardLayout: { imageWidth: 30, imagePosition: "left" },
        },
    },
    {
        id: "trade",
        name: "Trade Pro",
        description: "Financial trading terminal aesthetic. Monospace prices, ticker header, live trade ticket summary. Active band with pulsing green indicator.",
        defaults: {
            activeTheme: "trade",
            primaryColor: "#059669",
            accentColor: "#f59e0b",
            grid: { mobile: 1, tablet: 2, desktop: 2, wide: 3 },
            cardStyle: { borderRadius: "lg" },
            cardLayout: { imageWidth: 25, imagePosition: "left" },
        },
    },
    {
        id: "harvest",
        name: "Harvest",
        description: "Warm organic produce aesthetic. Cream/amber tones, hero images, tier tags as stacked ribbons. Active tag enlarged with accent color.",
        defaults: {
            activeTheme: "harvest",
            primaryColor: "#b45309",
            accentColor: "#059669",
            grid: { mobile: 1, tablet: 2, desktop: 3, wide: 4 },
            cardStyle: { borderRadius: "2xl" },
            cardLayout: { imageWidth: 35, imagePosition: "top" },
        },
    },
    {
        id: "premiumcompact",
        name: "Premium Compact",
        description: "Same Premium Wholesale DNA but ~40% shorter. Compact tier rows, smaller image, active tier highlighting + next-tier nudge.",
        defaults: {
            activeTheme: "premiumcompact",
            primaryColor: "#059669",
            accentColor: "#f97316",
            grid: { mobile: 1, tablet: 2, desktop: 2, wide: 3 },
            cardStyle: { borderRadius: "lg" },
            cardLayout: { imageWidth: 25, imagePosition: "left" },
        },
    },
    {
        id: "premiummini",
        name: "Premium Mini",
        description: "Ultra-compact with tier PILLS instead of rows. Everything tight. Active pill lights up green. Perfect for 2-column mobile grids.",
        defaults: {
            activeTheme: "premiummini",
            primaryColor: "#059669",
            accentColor: "#f97316",
            grid: { mobile: 2, tablet: 2, desktop: 3, wide: 4 },
            cardStyle: { borderRadius: "xl" },
            cardLayout: { imageWidth: 25, imagePosition: "left" },
        },
    },
    {
        id: "premiumdense",
        name: "Premium Dense",
        description: "Information-dense with 2-column tier grid. Active tier has emerald glow ring. Inline order total. ~50% shorter than original Premium.",
        defaults: {
            activeTheme: "premiumdense",
            primaryColor: "#059669",
            accentColor: "#f97316",
            grid: { mobile: 1, tablet: 2, desktop: 2, wide: 3 },
            cardStyle: { borderRadius: "lg" },
            cardLayout: { imageWidth: 25, imagePosition: "left" },
        },
    },
    {
        id: "premiumribbon",
        name: "Premium Ribbon",
        description: "Blue-indigo ribbon tabs for each tier. Active ribbon scales up with shadow. Left indigo accent border. Bold and modern.",
        defaults: {
            activeTheme: "premiumribbon",
            primaryColor: "#6366f1",
            accentColor: "#3b82f6",
            grid: { mobile: 1, tablet: 2, desktop: 2, wide: 3 },
            cardStyle: { borderRadius: "xl" },
            cardLayout: { imageWidth: 28, imagePosition: "left" },
        },
    },
    {
        id: "premiumticket",
        name: "Premium Ticket",
        description: "Warm sepia receipt-stub with monospace text, dashed tear-off, dot-leader lines and running total. Vintage charm.",
        defaults: {
            activeTheme: "premiumticket",
            primaryColor: "#b45309",
            accentColor: "#d97706",
            grid: { mobile: 1, tablet: 2, desktop: 2, wide: 3 },
            cardStyle: { borderRadius: "xl" },
            cardLayout: { imageWidth: 25, imagePosition: "left" },
        },
    },
    {
        id: "premiumshelf",
        name: "Premium Shelf",
        description: "Bold emerald header band with embedded price label. Vertical dot-connector ladder linking tier tags. Clean grocery shelf feel.",
        defaults: {
            activeTheme: "premiumshelf",
            primaryColor: "#059669",
            accentColor: "#f97316",
            grid: { mobile: 1, tablet: 2, desktop: 2, wide: 3 },
            cardStyle: { borderRadius: "lg" },
            cardLayout: { imageWidth: 25, imagePosition: "left" },
        },
    },
    {
        id: "zen",
        name: "Zen Garden",
        description: "Japanese-inspired minimal design. Warm stone tones, generous whitespace, ink-wash muted images. Tier pricing as stacked zen stones.",
        defaults: {
            activeTheme: "zen",
            primaryColor: "#7c8c6e",
            accentColor: "#a0856e",
            grid: { mobile: 1, tablet: 2, desktop: 3, wide: 3 },
            cardStyle: { borderRadius: "xl" },
            cardLayout: { imageWidth: 30, imagePosition: "left" },
        },
    },
    {
        id: "aurora",
        name: "Aurora Borealis",
        description: "Dark mode with flowing northern-lights gradients (purple-teal-green). Glowing tier badges, frosted dark glass. Celestial premium feel.",
        defaults: {
            activeTheme: "aurora",
            primaryColor: "#7c3aed",
            accentColor: "#06b6d4",
            grid: { mobile: 1, tablet: 2, desktop: 3, wide: 3 },
            cardStyle: { borderRadius: "xl" },
            cardLayout: { imageWidth: 30, imagePosition: "left" },
        },
    },
    {
        id: "terracotta",
        name: "Terracotta",
        description: "Warm Mediterranean pottery aesthetic. Burnt sienna and cream palette, arched image overlays, clay-textured tier blocks. Artisan market feel.",
        defaults: {
            activeTheme: "terracotta",
            primaryColor: "#c2703e",
            accentColor: "#6b8c42",
            grid: { mobile: 1, tablet: 2, desktop: 3, wide: 3 },
            cardStyle: { borderRadius: "xl" },
            cardLayout: { imageWidth: 35, imagePosition: "top" },
        },
    },
    {
        id: "sapphire",
        name: "Sapphire Night",
        description: "Deep navy dark theme with silver/platinum metallic pricing and sapphire blue active highlights. Luxury jewelry-store elegance.",
        defaults: {
            activeTheme: "sapphire",
            primaryColor: "#1e40af",
            accentColor: "#94a3b8",
            grid: { mobile: 1, tablet: 2, desktop: 2, wide: 3 },
            cardStyle: { borderRadius: "lg" },
            cardLayout: { imageWidth: 28, imagePosition: "left" },
        },
    },
    {
        id: "sakura",
        name: "Sakura Bloom",
        description: "Cherry blossom inspired soft pink and white. Petal-shaped tier badges, rose accents, gentle gradients. Light, airy and delicate.",
        defaults: {
            activeTheme: "sakura",
            primaryColor: "#ec4899",
            accentColor: "#e11d48",
            grid: { mobile: 1, tablet: 2, desktop: 3, wide: 4 },
            cardStyle: { borderRadius: "2xl" },
            cardLayout: { imageWidth: 35, imagePosition: "top" },
        },
    },
    {
        id: "mandichit",
        name: "Mandi Chit",
        description: "Auction-yard ticket aesthetic — cream paper, rotated ink-stamp categories, typewriter headline, big tabular price, dotted ledger slabs and a three-script Weigh & Add action. Culturally grounded.",
        featured: true,
        defaults: {
            activeTheme: "mandichit",
            primaryColor: "#1a1612",
            accentColor: "#a83b1a",
            grid: { mobile: 1, tablet: 2, desktop: 3, wide: 3 },
            cardStyle: { borderRadius: "none" },
            cardLayout: { imageWidth: 30, imagePosition: "left" },
        },
    },
    {
        id: "bulletin",
        name: "Daily Bulletin",
        description: "Broadsheet editorial — Fraunces serif headlines, italic tabular prices, two-column Today's Rate / Bulk Slabs body, sepia wire-photo crops, circular Save stamps angled diagonally. Slow, premium, intentional.",
        featured: true,
        defaults: {
            activeTheme: "bulletin",
            primaryColor: "#1c1a17",
            accentColor: "#b22222",
            grid: { mobile: 1, tablet: 2, desktop: 3, wide: 3 },
            cardStyle: { borderRadius: "none" },
            cardLayout: { imageWidth: 28, imagePosition: "right" },
        },
    },
    {
        id: "produceforward",
        name: "Produce Forward",
        description: "The food is the design — full-bleed dramatic crops, category-tinted backgrounds, Cormorant Garamond serif name + italic price, pill action and tier slabs that reveal on tap. Closer to a Whole Foods quarterly than a B2B tile.",
        featured: true,
        defaults: {
            activeTheme: "produceforward",
            primaryColor: "#0f3a2c",
            accentColor: "#f1f4ee",
            grid: { mobile: 1, tablet: 2, desktop: 3, wide: 3 },
            cardStyle: { borderRadius: "2xl" },
            cardLayout: { imageWidth: 100, imagePosition: "top" },
        },
    },
    {
        id: "chalkboard",
        name: "Chalkboard",
        description: "Restaurant slate menu — black slate background, white chalk hand-lettered name in Caveat, chalked price circle with hand-drawn arrow nudge, hash-mark tier dividers and yellow CTA. Bistro-special-of-the-day energy.",
        featured: true,
        defaults: {
            activeTheme: "chalkboard",
            primaryColor: "#ffd166",
            accentColor: "#ff6b6b",
            grid: { mobile: 1, tablet: 2, desktop: 3, wide: 3 },
            cardStyle: { borderRadius: "md" },
            cardLayout: { imageWidth: 30, imagePosition: "left" },
        },
    },
    {
        id: "risograph",
        name: "Risograph",
        description: "Two-ink overprint zine aesthetic — federal blue + fluorescent pink on cream paper. Halftone dot fills, slight misregistration, duotone product photo, Space Grotesk headline. Indie-print warmth.",
        featured: true,
        defaults: {
            activeTheme: "risograph",
            primaryColor: "#1d4e89",
            accentColor: "#ff48b0",
            grid: { mobile: 1, tablet: 2, desktop: 3, wide: 3 },
            cardStyle: { borderRadius: "none" },
            cardLayout: { imageWidth: 30, imagePosition: "left" },
        },
    },
    {
        id: "tradingcard",
        name: "Trading Card",
        description: "Holographic refractor border that animates, foil-shine sweep across the photo on hover, stat-block tier table, multilingual rarity tag per category. Pokemon / sports-card energy.",
        featured: true,
        defaults: {
            activeTheme: "tradingcard",
            primaryColor: "#06b6d4",
            accentColor: "#ff48b0",
            grid: { mobile: 1, tablet: 2, desktop: 3, wide: 3 },
            cardStyle: { borderRadius: "lg" },
            cardLayout: { imageWidth: 100, imagePosition: "top" },
        },
    },
    {
        id: "brutalistslab",
        name: "Brutalist Slab",
        description: "Concrete monolith — Bebas Neue full-width headline, single thick rule, massive bottom price block in solid black. No rounding, no shadows. For buyers who want the price now and nothing else.",
        featured: true,
        defaults: {
            activeTheme: "brutalistslab",
            primaryColor: "#0a0a0a",
            accentColor: "#c8c2b6",
            grid: { mobile: 1, tablet: 2, desktop: 3, wide: 3 },
            cardStyle: { borderRadius: "none" },
            cardLayout: { imageWidth: 35, imagePosition: "left" },
        },
    },
    {
        id: "bazaarposter",
        name: "Bazaar Poster",
        description: "Hand-painted Indian shopfront sign — saturated marigold + tomato + leaf palette, scalloped banner, DM Serif Display italic name, dashed price tag, multi-script crowded gloriously. Street vendor board energy.",
        featured: true,
        defaults: {
            activeTheme: "bazaarposter",
            primaryColor: "#dc2626",
            accentColor: "#fbbf24",
            grid: { mobile: 1, tablet: 2, desktop: 3, wide: 3 },
            cardStyle: { borderRadius: "none" },
            cardLayout: { imageWidth: 30, imagePosition: "left" },
        },
    },
    {
        id: "apothecary",
        name: "Apothecary",
        description: "Old herbalist label — cream linen, ornate ruled frame, EB Garamond italic with Latin scientific names, sepia hatched engraving photos and apothecary-style tier slabs. Refined and slow.",
        featured: true,
        defaults: {
            activeTheme: "apothecary",
            primaryColor: "#3a2818",
            accentColor: "#8b6f3a",
            grid: { mobile: 1, tablet: 2, desktop: 3, wide: 3 },
            cardStyle: { borderRadius: "none" },
            cardLayout: { imageWidth: 25, imagePosition: "right" },
        },
    },
    {
        id: "postalstamp",
        name: "Postal Stamp",
        description: "Vintage postage stamp — full perforated edge, denomination block in upper-right, INDIA POST country marking, postmark cancellation circle angled across the photo. JetBrains Mono caption rows.",
        featured: true,
        defaults: {
            activeTheme: "postalstamp",
            primaryColor: "#3d2817",
            accentColor: "#7a3015",
            grid: { mobile: 1, tablet: 2, desktop: 3, wide: 3 },
            cardStyle: { borderRadius: "none" },
            cardLayout: { imageWidth: 100, imagePosition: "top" },
        },
    },
    {
        id: "memosticky",
        name: "Memo Sticky",
        description: "Yellow sticky note pinned to the wall — saturated post-it yellow with subtle tilt, Kalam handwritten Devanagari-friendly type, blue-pen, highlighter stripe through price, pencil-box CTA, curl shadow corner. Personal kanban energy.",
        featured: true,
        defaults: {
            activeTheme: "memosticky",
            primaryColor: "#0b3a7a",
            accentColor: "#fff48d",
            grid: { mobile: 1, tablet: 2, desktop: 3, wide: 4 },
            cardStyle: { borderRadius: "none" },
            cardLayout: { imageWidth: 30, imagePosition: "left" },
        },
    },
    {
        id: "periodicelement",
        name: "Periodic Element",
        description: "Atomic-table cell — big atomic number (SKU id), giant two-letter symbol from initials, common name beneath, 'atomic mass' price, isotope-style tier sub-grid. Disciplined, scientific, scannable.",
        featured: true,
        defaults: {
            activeTheme: "periodicelement",
            primaryColor: "#0a0a0a",
            accentColor: "#16a34a",
            grid: { mobile: 1, tablet: 2, desktop: 3, wide: 4 },
            cardStyle: { borderRadius: "none" },
            cardLayout: { imageWidth: 25, imagePosition: "right" },
        },
    },
    {
        id: "hairlinemodern",
        name: "Hairline Modern",
        description: "Pure white, single 1px hairline border, IBM Plex Sans throughout, generous whitespace, no shadows or gradients. Restraint to a fault — the antithesis of the Bazaar Poster.",
        featured: true,
        defaults: {
            activeTheme: "hairlinemodern",
            primaryColor: "#0f172a",
            accentColor: "#e2e8f0",
            grid: { mobile: 1, tablet: 2, desktop: 3, wide: 4 },
            cardStyle: { borderRadius: "none" },
            cardLayout: { imageWidth: 100, imagePosition: "top" },
        },
    },
    {
        id: "freightmanifest",
        name: "Freight Manifest",
        description: "Industrial shipping-label aesthetic — Oswald-condensed display, ink charcoal on paperboard, burnt-orange QC stamp, corner brackets on photo, weight-band tier rate chart, decorative barcode strip. For buyers who value transparency and dispatch reliability.",
        featured: true,
        defaults: {
            activeTheme: "freightmanifest",
            primaryColor: "#2a2f36",
            accentColor: "#c84c00",
            grid: { mobile: 1, tablet: 2, desktop: 3, wide: 3 },
            cardStyle: { borderRadius: "lg" },
            cardLayout: { imageWidth: 100, imagePosition: "top" },
        },
    },
    {
        id: "truckarttailgate",
        name: "TruckArt Tailgate",
        description: "Indian lorry-back panel — saturated marigold, tomato and cobalt palette, scalloped frame, Horn-OK-Please chevron header, mirror-medallion price hub, tri-script names and a tailgate-striped CTA. Locally rooted, deliberately maximalist.",
        featured: true,
        defaults: {
            activeTheme: "truckarttailgate",
            primaryColor: "#7f1d1d",
            accentColor: "#fbbf24",
            grid: { mobile: 1, tablet: 2, desktop: 3, wide: 3 },
            cardStyle: { borderRadius: "none" },
            cardLayout: { imageWidth: 35, imagePosition: "left" },
        },
    },
    {
        id: "thermalreceipt",
        name: "Thermal Receipt",
        description: "58mm POS roll mimicry — off-white thermal paper with edge fade, JetBrains Mono throughout, dashed cut lines, dot-leader rate rows, CSS barcode footer and a red RETAIN-FOR-DISPATCH stamp. Brutally legible for 80-SKU 6am orders.",
        featured: true,
        defaults: {
            activeTheme: "thermalreceipt",
            primaryColor: "#1a1a1a",
            accentColor: "#b91c1c",
            grid: { mobile: 1, tablet: 2, desktop: 3, wide: 4 },
            cardStyle: { borderRadius: "none" },
            cardLayout: { imageWidth: 30, imagePosition: "left" },
        },
    },
];
